[package]
name = "soundtouch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
soundtouch-sys = {path = './soundtouch-sys'}

[workspace]
members =  ['.', './soundtouch-sys']